SELECT S.SERI_ID_SERVICIO, S.SERI_MODALIDAD_EMISION, 
S.SESI_ID_SERVICIO_ESTADO, S.SERV_SITUACION,
SD.SDEI_ID_SERVICIO_DETALLE, SD.CATI_ID_CATALOGO,
SD.SDEI_MONEDA, SD.SDEN_MONTO, SD.SDED_FECHA, SD.SDED_FECHA_FIN,
SD.SDEI_TIPO_EMISION, SD.SDEI_TIPO_DETALLE, SD.SDEI_CANTIDAD,
C.CATV_DESCRIPCION_GLOSA, C.CATV_DESCRIPCION_CONCEPTO, CAST(SD.SDED_FECHA_REGISTRO AS DATE) fec_registro
FROM ECOM.ECOM_SERVICIO S
INNER JOIN ECOM.ECOM_SERVICIO_DETALLE SD ON S.SERI_ID_SERVICIO = SD.SERI_ID_SERVICIO
INNER JOIN ECOM.ECOM_CATALOGO C ON SD.CATI_ID_CATALOGO = C.CATI_ID_CATALOGO
WHERE S.CONI_ID_CONTRATO = 196275 AND S.SERI_ID_SERVICIO = 57002 
AND (SD.SDED_FECHA_FIN IS NULL OR SD.SDED_FECHA_FIN > '2024-06-30') AND SD.SDEN_MONTO <> 0;

select * from ECOM.ECOM_TABLA_GENERAL
SELECT * FROM ECOM.ESTADO
/*
0	- Modalida de Emision
1	Modalidad Adelantada
2	Modalidad Vencida
3	Modalidad Postpago

1	1	Recurrente (Emision Mensual)
1	2	No Recurrente (Emision Unica)
1	3	No Recurrente (Emision Fraccionada)
1	4	Recurrente (Emision Anual)

3	0	- Tipos de Detalle de Servicio
3	1	Contrato Inicial
3	2	Variables
*/

select * from ECOM.ECOM_SERVICIO_DETALLE WHERE SERI_ID_SERVICIO = 67233

SELECT * FROM ECOM.ECOM_CATALOGO WHERE CATI_ID_CATALOGO = 40

SELECT COMD_DES_CONCEPTO FROM ECOM.COMPROBANTE_DET WHERE SERI_ID_SERVICIO = 67233

SELECT * FROM ECOM.ECOM_CONTROL_PAGO WHERE SERI_ID_SERVICIO = 67233


SELECT CP.CPGI_ID_CONTROL_PAGO, CP.SDEI_ID_SERVICIO_DETALLE, 
CP.CPGI_MONEDA, CPGN_MONTO, CPGI_ESTADO, CPGB_SITUACION, CPGV_PERIODO_CONSUMO,
CPGD_FECHA_CONSUMO_INI, CPGD_FECHA_CONSUMO_FIN
FROM ECOM.ECOM_CONTROL_PAGO CP
WHERE CP.SERI_ID_SERVICIO = 57002 AND CPGV_PERIODO_CONSUMO > '202406'
ORDER BY CP.CPGV_PERIODO_CONSUMO, CP.SDEI_ID_SERVICIO_DETALLE;


SELECT C.COMC_COD_COMPROBANTE, C.MONI_ID_MONEDA, C.COMV_PERIODO_COMPROBANTE,
C.COMC_IMPORTE_TOTAL_SOLES compro_total_soles, C.COMC_IMPORTE_TOTAL_USD compro_total_usb,
C.COMC_IMPORTE_SOLES, 
CD.COMD_COD_DETALLE, CD.SDEI_ID_SERVICIO_DETALLE,
CD.COMD_IMPORTE_TOTAL_SOL compro_det_total_soles, CD.COMD_IMPORTE_TOTAL_USD cpmpro_det_total_usb,
CD.COMD_IMPORTE_SOL,
CD.CPGI_ID_CONTROL_PAGO
FROM ECOM.COMPROBANTE C
INNER JOIN ECOM.COMPROBANTE_DET CD ON C.COMC_COD_COMPROBANTE = CD.COMC_COD_COMPROBANTE
WHERE C.COMV_PERIODO_COMPROBANTE > '202406' AND CD.SERI_ID_SERVICIO = 57002
AND C.ESTI_ID_ESTADO <> 11 AND C.COMC_TIPO_OPERACION IN ('C', 'A')
ORDER BY C.COMV_PERIODO_COMPROBANTE

SELECT CP.CPGI_ID_CONTROL_PAGO, CP.SDEI_ID_SERVICIO_DETALLE, 
CP.CPGI_MONEDA, CPGN_MONTO, CPGI_ESTADO, CPGB_SITUACION, CPGV_PERIODO_CONSUMO,
CPGD_FECHA_CONSUMO_INI, CPGD_FECHA_CONSUMO_FIN, SD.CATI_ID_CATALOGO
FROM ECOM.ECOM_CONTROL_PAGO CP
LEFT JOIN ECOM.ECOM_SERVICIO_DETALLE SD ON CP.SDEI_ID_SERVICIO_DETALLE = SD.SDEI_ID_SERVICIO_DETALLE
WHERE CP.SERI_ID_SERVICIO = 1940881 AND CPGN_MONTO <> 0 AND CPGV_PERIODO_CONSUMO > '202406' 
ORDER BY CP.CPGV_PERIODO_CONSUMO, CP.SDEI_ID_SERVICIO_DETALLE;

SELECT * FROM ECOM.COMPROBANTE_DET WHERE CPGI_ID_CONTROL_PAGO = 48742107 -- 14345891

SELECT C.COMC_COD_COMPROBANTE id_compro, C.MONI_ID_MONEDA moneda, C.COMV_PERIODO_COMPROBANTE periodo,
case when C.MONI_ID_MONEDA = 1 then C.COMC_IMPORTE_TOTAL_SOLES else C.COMC_IMPORTE_TOTAL_USD end compro_total, 
case when C.MONI_ID_MONEDA = 1 then C.COMC_IMPORTE_SOLES else C.COMC_IMPORTE_USD end compro_importe, 
CD.COMD_DES_CONCEPTO,
CD.SDEI_ID_SERVICIO_DETALLE id_ser_det,
case when C.MONI_ID_MONEDA = 1 then CD.COMD_IMPORTE_SOL else CD.COMD_IMPORTE_USD end compro_det,
case when C.MONI_ID_MONEDA = 1 then CD.COMD_IMPORTE_TOTAL_SOL else CD.COMD_IMPORTE_TOTAL_USD end compro_det_total,
CD.CPGI_ID_CONTROL_PAGO
FROM ECOM.COMPROBANTE C
INNER JOIN ECOM.COMPROBANTE_DET CD ON C.COMC_COD_COMPROBANTE = CD.COMC_COD_COMPROBANTE
WHERE C.COMC_COD_COMPROBANTE = 13383286


SELECT C.COMC_COD_COMPROBANTE id_compro, C.MONI_ID_MONEDA moneda, C.COMV_PERIODO_COMPROBANTE periodo,
case when C.MONI_ID_MONEDA = 1 then C.COMC_IMPORTE_TOTAL_SOLES else C.COMC_IMPORTE_TOTAL_USD end compro_total, 
case when C.MONI_ID_MONEDA = 1 then C.COMC_IMPORTE_SOLES else C.COMC_IMPORTE_USD end compro_importe, 
CD.COMD_DES_CONCEPTO,
CD.SDEI_ID_SERVICIO_DETALLE id_ser_det,
CD.COMD_IMPORTE_TOTAL_SOL compro_det_total_soles, CD.COMD_IMPORTE_TOTAL_USD cpmpro_det_total_usb,
CD.COMD_IMPORTE_SOL,
CD.CPGI_ID_CONTROL_PAGO
FROM ECOM.COMPROBANTE C
INNER JOIN ECOM.COMPROBANTE_DET CD ON C.COMC_COD_COMPROBANTE = CD.COMC_COD_COMPROBANTE
WHERE C.COMV_PERIODO_COMPROBANTE > '202406' AND CD.SERI_ID_SERVICIO = 498685
AND C.ESTI_ID_ESTADO <> 11 AND C.COMC_TIPO_OPERACION IN ('C', 'A')
ORDER BY C.COMV_PERIODO_COMPROBANTE

