UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1770;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (750, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1757;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1758;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1759;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (745, 270, 1, '02', 269.00, '02', '01', '01', '02', NULL, 270, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1741;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (731, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1753;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (743, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1742;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (732, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1752;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (742, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1735;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1736;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1737;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (729, 270, 1, '02', 269.00, '02', '01', '01', '02', NULL, 270, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1761;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1762;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1763;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (747, 270, 1, '02', 269.00, '02', '01', '01', '02', NULL, 270, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1767;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1768;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1769;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (749, 270, 1, '02', 269.00, '02', '01', '01', '02', NULL, 270, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1732;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1733;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1734;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (728, 270, 1, '02', 135.00, '02', '01', '01', '02', NULL, 270, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1743;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (733, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1738;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1739;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1740;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (730, 270, 1, '02', 269.00, '02', '01', '01', '02', NULL, 270, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1744;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (734, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1751;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (741, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1750;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (740, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1749;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (739, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1748;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (738, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1747;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (737, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1746;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (736, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1745;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (735, 269, 1, '01', 175.00, '02', '01', '01', '02', NULL, 269, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1754;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1755;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1756;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (744, 270, 1, '02', 269.00, '02', '01', '01', '02', NULL, 270, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1764;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1765;

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1766;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (748, 270, 1, '02', 269.00, '02', '01', '01', '02', NULL, 270, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

UPDATE CRM_VENTA_DETALLE SET VTDI_EST_REGISTRO = 0 WHERE VTDI_COD_VENTA_DETALLE = 1760;

INSERT INTO CRM_VENTA_DETALLE (VTDI_COD_VENTA, VTDI_COD_TARIFARIO, VTDI_CANTIDAD, VTDC_COD_TIPO_MONEDA, VTDN_PRECIO, VTDC_COD_TIPO_MODALIDAD, VTDC_COD_TIPO_NATURALEZA, TARC_COD_TIPO_RENTA, VTDC_COT_TIPO_CUOTAS, VTDI_CANTIDAD_CUOTAS, VTDI_COD_PAQUETE_PRODUCTO, VTDI_EST_REGISTRO, VTDV_USUARIO_CREACION, VTDD_FECHA_CREACION, VTDV_USUARIO_ACTUALIZACION, VTDD_FECHA_ACTUALIZACION, VTDD_FECHA_INICIO, VTDD_FECHA_FIN, VTDV_TIPO_PRODUCTO)
VALUES (746, 271, 1, '01', 125.00, '02', '01', '01', '02', NULL, 271, 1, 'migracion', NOW(), 'migracion', NOW(), '2024-12-31', NULL, '01');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (728, 'wincrm', '{"codpedido":728,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (728, 'winforce', '{"codpedido":728,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (729, 'wincrm', '{"codpedido":729,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (729, 'winforce', '{"codpedido":729,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (730, 'wincrm', '{"codpedido":730,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (730, 'winforce', '{"codpedido":730,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (731, 'wincrm', '{"codpedido":731,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (731, 'winforce', '{"codpedido":731,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (732, 'wincrm', '{"codpedido":732,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (732, 'winforce', '{"codpedido":732,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (733, 'wincrm', '{"codpedido":733,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (733, 'winforce', '{"codpedido":733,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (734, 'wincrm', '{"codpedido":734,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (734, 'winforce', '{"codpedido":734,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (735, 'wincrm', '{"codpedido":735,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (735, 'winforce', '{"codpedido":735,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (736, 'wincrm', '{"codpedido":736,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (736, 'winforce', '{"codpedido":736,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (737, 'wincrm', '{"codpedido":737,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (737, 'winforce', '{"codpedido":737,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (738, 'wincrm', '{"codpedido":738,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (738, 'winforce', '{"codpedido":738,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (739, 'wincrm', '{"codpedido":739,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (739, 'winforce', '{"codpedido":739,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (740, 'wincrm', '{"codpedido":740,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (740, 'winforce', '{"codpedido":740,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (741, 'wincrm', '{"codpedido":741,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (741, 'winforce', '{"codpedido":741,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (742, 'wincrm', '{"codpedido":742,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (742, 'winforce', '{"codpedido":742,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (743, 'wincrm', '{"codpedido":743,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (743, 'winforce', '{"codpedido":743,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (744, 'wincrm', '{"codpedido":744,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (744, 'winforce', '{"codpedido":744,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (745, 'wincrm', '{"codpedido":745,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (745, 'winforce', '{"codpedido":745,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (746, 'wincrm', '{"codpedido":746,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (746, 'winforce', '{"codpedido":746,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (747, 'wincrm', '{"codpedido":747,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (747, 'winforce', '{"codpedido":747,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (748, 'wincrm', '{"codpedido":748,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (748, 'winforce', '{"codpedido":748,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (749, 'wincrm', '{"codpedido":749,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (749, 'winforce', '{"codpedido":749,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`) 
VALUES (750, 'wincrm', '{"codpedido":750,"fechaInstalacion":"2024-12-31","horaIni":"20:20:20","horaFin":"20:20:20","fechaInstalacionReal":"2024-12-31","observaciones":"","codContrata":"1","nomContrata":"MIGRACION WIN-ULTRA","macRouter":"-","servicio_telefono":"","servicio_portabilidad":0,"codigo_generado":"0"}', 
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');

INSERT INTO CRM_CHECKLIST_ACTIVACION (`ACTI_COD_PEDIDO`, `ACTV_SERVICIO`, `ACTT_DATAJSON`, `ACTD_FECHA_INSERT`, `ACTD_FECHA_UPDATE`, 
`ACTI_INTENTO`, `ACTI_ESTADO`, `ACTV_ACCION`)
VALUES (750, 'winforce', '{"codpedido":750,"observaciones":"","servicio_telefono":"","servicio_portabilidad":0}',
'2024-12-31 20:20:20', '2024-12-31 20:20:20', 0, 0, 'activar');
